[build]
  command = "node build.js"
  publish = "public"

[[plugins]]
  package = "node-linux-x64"

[[headers]]
  for = "/*"
  [headers.values]
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
